fixtures:
  repositories:
    download_file: git://github.com/voxpupuli/puppet-download_file.git
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
  symlinks:
    windows_selenium_grid: "#{source_dir}"
